/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Clases.Persona_en_sesion;
import Clases.persona;
import Model.SqlUsuarios;
import Utilerias.hash;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author danie
 */
public class ActualizarDatosUsuario extends javax.swing.JFrame {

    /**
     * Creates new form ActualizarDatosUsuario
     */
    File fichero;
    String ruta;
    Persona_en_sesion per_ses;
    InicioAdmin frmIniAdm;
    InformacionUsuario frminformacionUsuario;

    public ActualizarDatosUsuario() {
        initComponents();
    }

    public ActualizarDatosUsuario(Persona_en_sesion per_ses) {
        this.per_ses = per_ses;
        initComponents();
        mostrardatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnactualizar = new javax.swing.JButton();
        btncargaimagen = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JPasswordField();
        txtConfContraseña = new javax.swing.JPasswordField();

        jLabel2.setText("Nombre:");

        jLabel3.setText("Apellido:");

        jLabel4.setText("Correo:");

        jLabel5.setText("Usuario:");

        jLabel6.setText("Contraseña:");

        jLabel7.setText("Confirmar contraseña:");

        jLabel8.setText("Imagen:");

        jButton1.setText("Regresar");

        jButton2.setText("Registrar");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Actualizar datos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Actualizar datos de usuario");

        jLabel9.setText("Nombre:");

        jLabel10.setText("Apellido:");

        jLabel11.setText("Correo:");

        jLabel13.setText("Contraseña:");

        jLabel14.setText("Confirmar contraseña:");

        jLabel15.setText("Imagen:");

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnactualizar.setText("Actualizar");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });

        btncargaimagen.setText("Seleccionar");
        btncargaimagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncargaimagenActionPerformed(evt);
            }
        });

        jLabel16.setText("Telefono");

        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });

        txtConfContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConfContraseñaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btncargaimagen, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(txtConfContraseña))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnRegresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(btnactualizar)
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel10))
                                .addGap(17, 17, 17)))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(txtTelefono)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtConfContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(btncargaimagen))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnactualizar)
                    .addComponent(btnRegresar))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        SqlUsuarios modSql = new SqlUsuarios();
        persona mod = new persona();
        FileInputStream fis = null;
        String correo = per_ses.getCorreo();
        String pass = new String(txtContraseña.getPassword());
        String confpass = new String(txtConfContraseña.getPassword());
        if (verificardatos(pass, confpass) == true) {
            if (fichero == null) {
                    String newpass = hash.hash1(pass);
                    mod.setNombre(txtNombre.getText());
                    mod.setApellido(txtApellido.getText());
                    mod.setTelefono(txtTelefono.getText());
                    mod.setCorreo(txtCorreo.getText());
                    mod.setContraseña(newpass);
                    mod.setTipo_usuario(per_ses.getTipo_usuario());
                    if (modSql.actualizar(mod, correo)) {
                        JOptionPane.showMessageDialog(null, "Actualizado");
                        per_ses.setNombre(mod.getNombre());
                        per_ses.setApellido(mod.getApellido());
                        per_ses.setCorreo(mod.getCorreo());
                        per_ses.setTelefono(mod.getTelefono());
                        per_ses.setContraseña(mod.getContraseña());
                        if (this.per_ses.getTipo_usuario() == 1) {
                            if (frmIniAdm == null) {
                                frmIniAdm = new InicioAdmin(this.per_ses);
                                frmIniAdm.setVisible(true);
                                this.dispose();
                            }
                        } else if (per_ses.getTipo_usuario() == 2 || per_ses.getTipo_usuario() == 0) {
                            if (frminformacionUsuario == null) {
                                frminformacionUsuario = new InformacionUsuario(per_ses);
                                frminformacionUsuario.setVisible(true);
                                this.dispose();
                            }
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "error");
                    }
            } else {
                try {
                    fis = new FileInputStream(fichero);
                    String newpass = hash.hash1(pass);
                    mod.setNombre(txtNombre.getText());
                    mod.setApellido(txtApellido.getText());
                    mod.setTelefono(txtTelefono.getText());
                    mod.setCorreo(txtCorreo.getText());
                    mod.setContraseña(newpass);
                    mod.setImagen((int) fichero.length());
                    mod.setTipo_usuario(per_ses.getTipo_usuario());
                    if (modSql.actualizar(mod, fis, correo)) {
                        JOptionPane.showMessageDialog(null, "Actualizado");
                        per_ses.setNombre(mod.getNombre());
                        per_ses.setApellido(mod.getApellido());
                        per_ses.setCorreo(mod.getCorreo());
                        per_ses.setTelefono(mod.getTelefono());
                        per_ses.setContraseña(mod.getContraseña());
                        per_ses.setImagen(mod.getImagen());
                        if (this.per_ses.getTipo_usuario() == 1) {
                            if (frmIniAdm == null) {
                                frmIniAdm = new InicioAdmin(this.per_ses);
                                frmIniAdm.setVisible(true);
                                this.dispose();
                            }
                        } else if (per_ses.getTipo_usuario() == 2 || per_ses.getTipo_usuario() == 0) {
                            if (frminformacionUsuario == null) {
                                frminformacionUsuario = new InformacionUsuario(per_ses);
                                frminformacionUsuario.setVisible(true);
                                this.dispose();
                            }
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "error");
                    }
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(ActualizarDatosUsuario.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    try {
                        fis.close();
                    } catch (IOException ex) {
                        Logger.getLogger(ActualizarDatosUsuario.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }


    }//GEN-LAST:event_btnactualizarActionPerformed

    private void txtConfContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConfContraseñaActionPerformed

    private void btncargaimagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncargaimagenActionPerformed

        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        int seleccion = fc.showOpenDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            fichero = fc.getSelectedFile();
            ruta = fichero.getAbsolutePath();
        } else {
            JOptionPane.showMessageDialog(null, "no se pudo cargar la imagen");
        }
    }//GEN-LAST:event_btncargaimagenActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        if (this.per_ses.getTipo_usuario() == 1) {
            if (frmIniAdm == null) {
                frmIniAdm = new InicioAdmin(this.per_ses);
                frmIniAdm.setVisible(true);
                this.dispose();
            }
        } else if (per_ses.getTipo_usuario() == 2 || per_ses.getTipo_usuario() == 0) {
            if (frminformacionUsuario == null) {
                frminformacionUsuario = new InformacionUsuario(per_ses);
                frminformacionUsuario.setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (this.per_ses.getTipo_usuario() == 1) {
            if (frmIniAdm == null) {
                frmIniAdm = new InicioAdmin(this.per_ses);
                frmIniAdm.setVisible(true);
                this.dispose();
            }
        } else if (per_ses.getTipo_usuario() == 2 || per_ses.getTipo_usuario() == 0) {
            if (frminformacionUsuario == null) {
                frminformacionUsuario = new InformacionUsuario(per_ses);
                frminformacionUsuario.setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarDatosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarDatosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarDatosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarDatosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarDatosUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btncargaimagen;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JPasswordField txtConfContraseña;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

    private void mostrardatos() {

        txtNombre.setText(per_ses.getNombre());
        txtApellido.setText(per_ses.getApellido());
        txtCorreo.setText(per_ses.getCorreo());
        txtTelefono.setText(per_ses.getTelefono());

    }

    private boolean verificardatos(String pass, String confpass) {
        if (txtNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe de ingresar su nombre");
            return false;
        }
        if (txtApellido.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe de ingresar su Apellido");
            return false;
        }
        if (txtTelefono.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe de ingresar su Telefono");
            return false;
        }
        if (txtCorreo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe de ingresar su Correo");
            return false;
        }
        if (!pass.equalsIgnoreCase(confpass)) {
            JOptionPane.showMessageDialog(null, "Las contraseñas deben de ser iguales");
            return false;
        }
        return true;
    }
}
