/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Clases.Persona_en_sesion;
import Clases.quejas;
import Model.Conexion;
import com.mysql.jdbc.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author feth
 */
public class MostrarQuejas extends javax.swing.JFrame {

    DefaultTableModel model;
    int Id_usuario;
    int Id_queja;
    protected static quejas quejaResponder;
    Persona_en_sesion per_ses;
    RespuestaQueja respQueja;
    InicioAdmin frmInicioAdmin;
    InformacionUsuario frminformacionUsuario;
    FormularioQuejas frmformularioQuejas;

    /**
     * Creates new form MostrarQuejas
     */
    public MostrarQuejas() {
        initComponents();

        cargar();

    }

    public MostrarQuejas(Persona_en_sesion per) {
        this.per_ses = per;
        initComponents();

        cargar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaQuejas = new javax.swing.JTable();
        txtTitulo = new javax.swing.JTextField();
        btnResponder = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMensaje = new javax.swing.JTextArea();

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Confirmación de pago");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quejas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Mostrar quejas");

        tablaQuejas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaQuejas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaQuejasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaQuejas);

        btnResponder.setText("Responder");
        btnResponder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResponderActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        txtMensaje.setColumns(20);
        txtMensaje.setRows(5);
        jScrollPane2.setViewportView(txtMensaje);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnResponder))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(135, 135, 135)
                                .addComponent(btnRegresar)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addGap(14, 14, 14))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(162, Short.MAX_VALUE)
                    .addComponent(jLabel9)
                    .addContainerGap(162, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegresar)
                        .addGap(18, 18, 18)))
                .addComponent(btnResponder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel9)
                    .addContainerGap(379, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaQuejasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaQuejasMouseClicked
        // TODO add your handling code here:

        //Limpiar
        txtTitulo.setText(null);

        int set = tablaQuejas.getSelectedRow();
        txtTitulo.setText(tablaQuejas.getModel().getValueAt(set, 0).toString());
        txtTitulo.setEditable(false);
        txtMensaje.setText(tablaQuejas.getModel().getValueAt(set, 1).toString());
        txtMensaje.setEditable(false);
        txtMensaje.setLineWrap(true);
        // Id_usuario = Integer.parseInt(tablaQuejas.getModel().getValueAt(set, 2).toString());
        //Id_queja = Integer.parseInt(tablaQuejas.getModel().getValueAt(set, 3).toString());

    }//GEN-LAST:event_tablaQuejasMouseClicked

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        System.out.println(frminformacionUsuario);
        System.out.println(per_ses.getTipo_usuario());
        if (per_ses.getTipo_usuario() == 1) {
            if (frmInicioAdmin == null) {
                frmInicioAdmin = new InicioAdmin(per_ses);
                frmInicioAdmin.setVisible(true);
                this.dispose();
            }

        }
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnResponderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResponderActionPerformed

        if (txtTitulo.getText().length() == 0 || txtMensaje.getText().length() == 0) {

            JOptionPane.showMessageDialog(null, "Por favor, selecciona una queja");

        } else {

            quejaResponder = new quejas();

            quejaResponder.setTitulo(txtTitulo.getText());
            quejaResponder.setDescripcion(txtMensaje.getText());
            //quejaResponder.setId_usuario(Id_usuario);
            //quejaResponder.setId(Id_queja);
            quejaResponder.setId_admin(per_ses.getId());

            //if(respQueja==null){
            respQueja = new RespuestaQueja(per_ses);

            //Hacemos visible la nueva interfaz
            respQueja.setVisible(true);
            //Cerramos la actual
            dispose();
            //}

        }


    }//GEN-LAST:event_btnResponderActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (per_ses.getTipo_usuario() == 1) {
            if (frmInicioAdmin == null) {
                frmInicioAdmin = new InicioAdmin(per_ses);
                frmInicioAdmin.setVisible(true);
                this.dispose();
            }

        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarQuejas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarQuejas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarQuejas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarQuejas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarQuejas().setVisible(true);
            }
        });
    }

    public void cargar() {

        String[] titulos = {"Queja", "Mensaje", "Respondido"}; //"ID del usuario", "ID de queja"};
        String[] registros = new String[100];

        String sql = "SELECT * FROM `Quejas`";

        model = new DefaultTableModel(null, titulos);

        //Conectar a base de datos
        Conexion cc = new Conexion();
        Connection conect = cc.getConexion();

        try {

            Statement st = (Statement) conect.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {

                registros[0] = rs.getString("Titulo");
                registros[1] = rs.getString("Descripcion");
                if (rs.getString("Respuesta") == null) {
                    registros[2] = "No contestado";
                } else {
                    registros[2] = "Contestado";
                }

                // registros[3] = rs.getString("Id_Queja");
                model.addRow(registros);
                //System.out.println(registros[3]);
            }

            tablaQuejas.setModel(model);

        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(null, ex);

        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnResponder;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaQuejas;
    private javax.swing.JTextArea txtMensaje;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables

    
}
