/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;


import Clases.Persona_en_sesion;
import Clases.quejas;
import Model.Conexion;
import com.mysql.jdbc.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;


/**
 *
 * @author danie
 */
public class RespuestaQueja extends javax.swing.JFrame {

    quejas respQueja = MostrarQuejas.quejaResponder;
    Persona_en_sesion per_ses;
    
    /**
     * Creates new form RespuestaQueja
     */
    public RespuestaQueja() {
        initComponents();
        
        txtQueja.setText( respQueja.getDescripcion() );
        
    }
    public RespuestaQueja(Persona_en_sesion per) {
        this.per_ses=per;
        initComponents();
        
        txtQueja.setText( respQueja.getDescripcion() );
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtQueja = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        BotonRegresar = new javax.swing.JButton();
        BotonEnviar = new javax.swing.JButton();
        txtRespuesta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Respuesta a queja");

        jLabel2.setText("Queja:");

        txtQueja.setEditable(false);
        txtQueja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuejaActionPerformed(evt);
            }
        });

        jLabel3.setText("Respuesta:");

        BotonRegresar.setText("Regresar");
        BotonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegresarActionPerformed(evt);
            }
        });

        BotonEnviar.setText("Enviar");
        BotonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonRegresar)
                .addGap(80, 80, 80)
                .addComponent(BotonEnviar)
                .addGap(84, 84, 84))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel1)
                        .addGap(52, 52, 52))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQueja, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(txtRespuesta)))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtQueja, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtRespuesta, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonRegresar)
                    .addComponent(BotonEnviar))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEnviarActionPerformed
        // TODO add your handling code here:
        
        if( txtRespuesta.getText().length() == 0 ) {
            
            JOptionPane.showMessageDialog(null, "Escribe una repsuesta por favor");
            
        }
        
        else {
            
            Conexion objcon = new Conexion();
            Connection con = objcon.getConexion();
           // int Id_admin = respQueja.getId_admin();
            //int Id_qj = respQueja.getId();
            
            try {
                
                //String sql = "UPDATE Quejas SET Respuesta=?, Id_admin=?" + "WHERE Id_queja=?";
                String sql = "UPDATE Quejas SET Respuesta=?, Id_admin=? WHERE Titulo=? AND Descripcion=?";
                PreparedStatement prest = null;
                prest = con.prepareStatement(sql);
                
                prest.setString(1, txtRespuesta.getText());
                prest.setInt(2, per_ses.getId());
                //prest.setString(2, (String.valueOf(Id_admin)));
                //prest.setString(3, (String.valueOf(Id_qj)));
                prest.setString(3, respQueja.getTitulo());
                prest.setString(4, respQueja.getDescripcion());

                if (prest.executeUpdate() > 0)  {
                    
                    JOptionPane.showMessageDialog(null, "Respuesta enviada");

                    MostrarQuejas mostQuejas = new MostrarQuejas(per_ses);
        
                    //Hacemos visible la nueva interfaz
                    mostQuejas.setVisible(true);
                    //Cerramos la actual
                    dispose();

                } else{
                    
                    JOptionPane.showMessageDialog(null, "Falla al enviar Respuesta");
                    
                } 
                
            } catch( SQLException e) {
                
                JOptionPane.showMessageDialog(null, "Falla al enviar Respuesta");
                       
            } finally {
                
                if( con != null ) {
                    
                    try {
                        
                        con.close();
                        
                    } catch(SQLException e) {
                        
                        JOptionPane.showMessageDialog(null, "Falla al enviar Respuesta");
                        
                    }
                    
                }
                
            }
            
        }
        
    }//GEN-LAST:event_BotonEnviarActionPerformed

    private void txtQuejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuejaActionPerformed
        // TODO add your handling code here:
        
        txtQueja.setText( respQueja.getDescripcion() );
        
    }//GEN-LAST:event_txtQuejaActionPerformed

    private void BotonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegresarActionPerformed
        MostrarQuejas frmRegreso=new MostrarQuejas(per_ses);
        frmRegreso.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RespuestaQueja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RespuestaQueja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RespuestaQueja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RespuestaQueja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RespuestaQueja().setVisible(true);
            }
        });
        
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonEnviar;
    private javax.swing.JButton BotonRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtQueja;
    private javax.swing.JTextField txtRespuesta;
    // End of variables declaration//GEN-END:variables
}
